[package]
edition = "2021"
name = "rustycan_demo"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustycan_macro = {path = '../rustycan_macro'}
egui = "0.19.0"
egui-macroquad = "0.12.0"
macroquad = "0.3.25"